<?php

function openpublish_disqus_enable($disqus_domain) {
  //set domain
  variable_set("disqus_domain", $disqus_domain);
  //set default nodetypes
  $disqus_nodetypes = array(
  'openpublish_article'=>'openpublish_article',
  'openpublish_blog_post' =>'openpublish_blog_post',
  'openpublish_video' => 'openpublish_video',
  'openpublish_photo_gallery' => 'openpublish_photo_gallery',
  );
  variable_set("disqus_nodetypes", $disqus_nodetypes);
  //turn off drupal comments
  module_disable(array("comment"));
  //set perms
  $roles = array_flip(user_roles());
  user_role_grant_permissions($roles['anonymous user'], array('view disqus comments'));
  user_role_grant_permissions($roles['authenticated user'], array('view disqus comments'));
  

}
