name = OpenPublish Disqus
description = Set up Disqus-based commenting for an OpenPublish site.
machine_name = openpublish_disqus
version = 1.0
downloadable = openpublish_disqus
author = Phase2 Technology
author_url = http://www.phase2technology.com/
dependencies[disqus] = disqus 1.9
downloadables[openpublish_disqus] = http://appserver.openpublishapp.com/app/download/openpublish_disqus.tar.gz
downloadables[disqus 1.9] = http://ftp.drupal.org/files/projects/disqus-7.x-1.9.tar.gz
